server.port=8081
spring.application.name=ms-suscripciones

# Base de datos H2 (En memoria, no requiere instalación)
spring.datasource.url=jdbc:h2:mem:suscripciones_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Kafka (Event-Driven Architecture)
#spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

management.endpoints.web.exposure.include=health,info
